export const openrouterModels = [
  {
    name: "nvidia/llama-3.1-nemotron-ultra-253b-v1:free",
    displayName: "Llama 3.1 Nemotron Ultra 253b V1",
    hasVision: false,
    price: { input: 1, output: 1 },
    maxOutputTokens: 131000,
    contextWindow: 131000,
    supportsTool: true,
    speed: 25,
  },
  {
    name: "deepseek/deepseek-chat-v3-0324:free",
    displayName: "DeepSeek Chat V3 0324",
    hasVision: false,
    price: { input: 1, output: 1 },
    maxOutputTokens: 128000,
    contextWindow: 128000,
    supportsTool: true,
    speed: 60,
  },
  {
    name: "meta-llama/llama-4-maverick:free",
    displayName: "Meta Llama 4 Maverick",
    hasVision: false,
    price: { input: 1, output: 1 },
    maxOutputTokens: 256000,
    contextWindow: 256000,
    supportsTool: true,
    speed: 80,
  },
  {
    name: "openai/o4-mini-high",
    displayName: "OpenAI: o4 Mini High",
    hasVision: false,
    price: { input: 1.1 * 8, output: 4.4 * 8 },
    maxOutputTokens: 128000,
    contextWindow: 200000,
    supportsTool: true,
  },
  {
    name: "anthropic/claude-opus-4",
    displayName: "Anthropic: Claude Opus 4",
    hasVision: true,
    price: { input: 15 * 8, output: 75 * 8 },
    maxOutputTokens: 200000,
    contextWindow: 200000,
    supportsTool: true,
    pricePerImage: 24 * 8,
  },
  {
    name: "anthropic/claude-sonnet-4",
    displayName: "Anthropic: Claude Sonnet 4",
    hasVision: true,
    price: { input: 3 * 8, output: 15 * 8 },
    maxOutputTokens: 200000,
    contextWindow: 200000,
    supportsTool: true,
    pricePerImage: 4.8 * 8,
  },
  {
    // 不要删除 - 客户特殊需要
    name: "anthropic/claude-3.5-sonnet",
    displayName: "Anthropic: Claude 3.5 Sonnet",
    hasVision: true,
    price: { input: 3 * 8, output: 15 * 8 },
    maxOutputTokens: 200000,
    contextWindow: 200000,
    supportsTool: true,
    pricePerImage: 4.8 * 8,
  },
  {
    // 不要删除 - 客户特殊需要
    name: "anthropic/claude-3.5-sonnet-20240620",
    displayName: "Anthropic: Claude 3.5 Sonnet (2024-06-20)",
    hasVision: true,
    price: { input: 3 * 8, output: 15 * 8 },
    maxOutputTokens: 200000,
    contextWindow: 200000,
    supportsTool: true,
    pricePerImage: 4.8 * 8,
  },
  {
    name: "deepseek/deepseek-r1-0528:free",
    displayName: "DeepSeek: R1 0528 (free)",
    hasVision: false,
    price: { input: 1, output: 1 },
    maxOutputTokens: 163840,
    contextWindow: 163840,
    supportsTool: true,
  },
  {
    name: "anthropic/claude-3.7-sonnet:thinking",
    displayName: "Anthropic: Claude 3.7 Sonnet",
    hasVision: true,
    price: { input: 3 * 8, output: 15 * 8 },
    maxOutputTokens: 200000,
    contextWindow: 200000,
    supportsTool: true,
    pricePerImage: 4.8 * 8,
  },
  {
    name: "minimax/minimax-m1",
    displayName: "MiniMax: MiniMax M1",
    hasVision: false,
    price: { input: 0.3 * 8, output: 1.65 * 8 },
    maxOutputTokens: 1000000,
    contextWindow: 1000000,
    supportsTool: true,
  },
];
