export const openrouterModels = [
  {
    name: "anthropic/claude-3.7-sonnet",
    displayName: "Anthropic: Claude 3.7 Sonnet",
    hasVision: true,
    price: { input: 3 * 8, output: 15 * 8 },
    maxOutputTokens: 200000,
    contextWindow: 200000,
    supportsTool: true,
  },
  {
    name: "anthropic/claude-3.5-sonnet",
    displayName: "Anthropic: Claude 3.5 Sonnet",
    hasVision: true,
    price: { input: 3 * 8, output: 15 * 8 },
    maxOutputTokens: 200000,
    contextWindow: 200000,
    supportsTool: true,
    pricePerImage: 4.8 * 8,
  },
  {
    name: "google/gemini-2.5-pro-exp-03-25:free",
    displayName: "Gemini 2.5 Pro Exp 03-25",
    hasVision: false,
    price: { input: 1, output: 1 },
    maxOutputTokens: 66000,
    contextWindow: 1000000,
    supportsTool: true,
  },
  {
    name: "nvidia/llama-3.1-nemotron-ultra-253b-v1:free",
    displayName: "Llama 3.1 Nemotron Ultra 253b V1",
    hasVision: false,
    price: { input: 1, output: 1 },
    maxOutputTokens: 131000,
    contextWindow: 131000,
    supportsTool: true,
    speed: 25,
  },
  {
    name: "deepseek/deepseek-chat-v3-0324:free",
    displayName: "DeepSeek Chat V3 0324",
    hasVision: false,
    price: { input: 1, output: 1 },
    maxOutputTokens: 128000,
    contextWindow: 128000,
    supportsTool: true,
    speed: 60,
  },
  {
    name: "meta-llama/llama-4-maverick:free",
    displayName: "Meta Llama 4 Maverick",
    hasVision: false,
    price: { input: 1, output: 1 },
    maxOutputTokens: 256000,
    contextWindow: 256000,
    supportsTool: true,
    speed: 80,
  },
  {
    name: "deepseek/deepseek-r1:free",
    displayName: "DeepSeek R1",
    hasVision: false,
    price: { input: 1, output: 1 },
    maxOutputTokens: 164000,
    contextWindow: 164000,
    supportsTool: true,
    speed: 10,
  },
  {
    name: "openai/o4-mini-high",
    displayName: "OpenAI: o4 Mini High",
    hasVision: false,
    price: { input: 1.1 * 8, output: 4.4 * 8 },
    maxOutputTokens: 128000,
    contextWindow: 200000,
    supportsTool: true,
  },
  {
    name: "openai/gpt-4.1",
    displayName: "GPT-4.1",
    hasVision: true,
    contextWindow: 1047576,
    maxOutputTokens: 32768,
    price: {
      input: 16.0,
      output: 64.0,
      inputCacheHit: 4.0,
    },
    supportsTool: true,
  },
  {
    name: "openai/gpt-4.1-mini",
    displayName: "GPT-4.1 Mini",
    hasVision: true,
    contextWindow: 1047576,
    maxOutputTokens: 32768,
    price: {
      input: 3.2,
      output: 12.8,
      inputCacheHit: 0.8,
    },
    supportsTool: true,
  },
  {
    name: "openai/gpt-4.1-nano",
    displayName: "GPT-4.1 Nano",
    hasVision: true,
    contextWindow: 1047576,
    maxOutputTokens: 32768,
    price: {
      input: 0.8,
      output: 3.2,
      inputCacheHit: 0.2,
    },
    supportsTool: true,
  },
];
