export const claudeModels = {
  "claude-3-5-sonnet-20240620": {
    description: "Most intelligent model",
    strengths: "Highest level of intelligence and capability",
    multilingual: "Yes",
    vision: "Yes",
    apiModelName: "claude-3-5-sonnet-20240620",
    apiFormat: "Messages API",
    comparativeLatency: "Fast",
    contextWindow: "",
    maxOutput: "",
    trainingDataCutOff: "Apr 2024",
    input: 3.0,
    output: 15.0,
  },
  //   "claude-3-opus-20240229": {
  //     description: "Powerful model for highly complex tasks",
  //     strengths:
  //       "Top-level performance, intelligence, fluency, and understanding",
  //     multilingual: "Yes",
  //     vision: "Yes",
  //     apiModelName: "claude-3-opus-20240229",
  //     apiFormat: "Messages API",
  //     comparativeLatency: "Moderately fast",
  //     contextWindow: "",
  //     maxOutput: "",
  //     trainingDataCutOff: "Aug 2023",
  //     input: 15.0,
  //     output: 75.0,
  //   },
  "claude-3-sonnet-20240229": {
    description: "Balance of intelligence and speed",
    strengths: "Strong utility, balanced for scaled deployments",
    multilingual: "Yes",
    vision: "Yes",
    apiModelName: "claude-3-sonnet-20240229",
    apiFormat: "Messages API",
    comparativeLatency: "Fast",
    contextWindow: "",
    maxOutput: "",
    trainingDataCutOff: "Aug 2023",
    input: 3.0,
    output: 15.0,
  },
  "claude-3-haiku-20240307": {
    description:
      "Fastest and most compact model for near-instant responsiveness",
    strengths: "Quick and accurate targeted performance",
    multilingual: "Yes",
    vision: "Yes",
    apiModelName: "claude-3-haiku-20240307",
    apiFormat: "Messages API",
    comparativeLatency: "Fastest",
    contextWindow: "",
    maxOutput: "",
    trainingDataCutOff: "Aug 2023",
    input: 0.25,
    output: 1.25,
  },
};
