export const initialModels = [
  {
    name: "Mistral Large",
    maxOutputTokens: "8k",
    contextWindow: "128k",
    humanEval: "92.1",
    outputPrice: "6",
    inputPrice: "2",
    supportsTool: "是",
    visualCapability: "未知",
    latency: "未知",
  },
  {
    name: "mistral-nemo",
    maxOutputTokens: "8k",
    contextWindow: "128k",
    humanEval: "未知",
    outputPrice: "0.15",
    inputPrice: "0.15",
    supportsTool: "是",
    visualCapability: "未知",
    latency: "未知",
  },
  {
    name: "Pixtral 12B",
    maxOutputTokens: "8k",
    contextWindow: "128k",
    humanEval: "未知",
    outputPrice: "0.15",
    inputPrice: "0.15",
    supportsTool: "是",
    visualCapability: "未知",
    latency: "未知",
  },
  {
    name: "Llama-3.2-90B-Vision",
    maxOutputTokens: "8k",
    contextWindow: "未知",
    humanEval: "未知",
    outputPrice: "0.40",
    inputPrice: "0.35",
    supportsTool: "是",
    visualCapability: "是",
    latency: "未知",
  },
  {
    name: "LLaMA 70B",
    maxOutputTokens: "8k",
    contextWindow: "未知",
    humanEval: "80.5",
    outputPrice: "0.40",
    inputPrice: "0.35",
    supportsTool: "是",
    visualCapability: "未知",
    latency: "未知",
  },
  {
    name: "LLaMA 405B",
    maxOutputTokens: "8k",
    contextWindow: "未知",
    humanEval: "89",
    outputPrice: "1.79",
    inputPrice: "1.79",
    supportsTool: "是",
    visualCapability: "未知",
    latency: "未知",
  },
  {
    name: "Claude 3.5 Sonnet",
    maxOutputTokens: "8k",
    contextWindow: "200k",
    humanEval: "92",
    outputPrice: "15",
    inputPrice: "3.75",
    supportsTool: "是",
    visualCapability: "是",
    latency: "未知",
  },
  {
    name: "GPT4-O",
    maxOutputTokens: "8k",
    contextWindow: "128k",
    humanEval: "90.2",
    outputPrice: "10",
    inputPrice: "2.5",
    supportsTool: "未知",
    visualCapability: "未知",
    latency: "未知",
  },
  {
    name: "GPT4-O Mini",
    maxOutputTokens: "8k",
    contextWindow: "128k",
    humanEval: "88.4",
    outputPrice: "0.60",
    inputPrice: "0.15",
    supportsTool: "未知",
    visualCapability: "未知",
    latency: "未知",
  },
  {
    name: "Gimini 1.5 Pro",
    maxOutputTokens: "8k",
    contextWindow: "2m",
    humanEval: "84.1",
    outputPrice: "5.00",
    inputPrice: "1.25",
    supportsTool: "未知",
    visualCapability: "是",
    latency: "未知",
  },
  {
    name: "Gimini 1.5 Flash",
    maxOutputTokens: "8k",
    contextWindow: "1m",
    humanEval: "74.3",
    outputPrice: "0.30",
    inputPrice: "0.075",
    supportsTool: "是",
    visualCapability: "是",
    latency: "未知",
  },
  {
    name: "Qwen 2.5",
    maxOutputTokens: "8k",
    contextWindow: "32K",
    humanEval: "86.6",
    outputPrice: "0.4",
    inputPrice: "0.35",
    supportsTool: "是",
    visualCapability: "未知",
    latency: "未知",
  },
  {
    name: "DeepSeek 2.5",
    maxOutputTokens: "8k",
    contextWindow: "128k",
    humanEval: "89",
    outputPrice: "0.28",
    inputPrice: "0.14",
    supportsTool: "是",
    visualCapability: "未知",
    latency: "未知",
  },
  {
    name: "O1-Preview",
    maxOutputTokens: "128k",
    contextWindow: "128k",
    humanEval: "92.4",
    outputPrice: "60.00",
    inputPrice: "15.00",
    supportsTool: "是",
    visualCapability: "否",
    latency: "未知",
  },
  {
    name: "O1-Mini",
    maxOutputTokens: "128k",
    contextWindow: "128k",
    humanEval: "92.4",
    outputPrice: "12.00",
    inputPrice: "3.00",
    supportsTool: "是",
    visualCapability: "否",
    latency: "未知",
  },
];
